<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d71ce128d276',
	'title' => 'Lesson Group',
	'fields' => array(
		array(
			'key' => 'field_5d71ce2536d8f',
			'label' => 'Student',
			'name' => 'select_user',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				2 => 'bloops',
				6 => 'Chris Wieber',
				5 => 'noodles',
				3 => 'nuggets',
				4 => 'test',
				1 => 'twocodachris',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'label',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d71cf7dc4a14',
			'label' => 'Location',
			'name' => 'lesson_page_location',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Online' => 'Online',
				'Castle Greyskull' => 'Castle Greyskull',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'label',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d71d038d12dc',
			'label' => 'Type of Lesson',
			'name' => 'type_of_lesson',
			'type' => 'select',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'30min Cello Lesson' => '30min Cello Lesson',
				'60min Clarinet Lesson' => '60min Clarinet Lesson',
				'90min Oboe Lesson' => '90min Oboe Lesson',
			),
			'default_value' => array(
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 1,
			'ajax' => 1,
			'return_format' => 'label',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5d71d0ffd12dd',
			'label' => 'Date and Time',
			'name' => 'date_and_time',
			'type' => 'date_time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y g:i a',
			'return_format' => 'd/m/Y g:i a',
			'first_day' => 1,
		),
		array(
			'key' => 'field_5d71d12ed12de',
			'label' => 'Notes',
			'name' => 'notes',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'tc-lesson',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
));

endif;